Repository Saakshaat/umass-match, pull requests merged in 2020-12, with the labels that each got.

#1 Initialize server
  server/.gitignore
  server/Dockerfile
  server/Pipfile
  server/Pipfile.lock
  server/README.md
  server/docker-compose.test.yml
  server/main.py
  server/models/__init__.py
  server/resources/__init__.py
  server/resources/api/__init__.py
  server/resources/crud/__init__.py
  server/resources/db.py
  server/schemas/__init__.py
Labels: backend, enhancement

#3 User resource
  server/models/__init__.py
  server/models/base.py
  server/models/user.py
  server/resources/api/__init__.py
  server/resources/api/user.py
  server/resources/crud/create.py
  server/resources/crud/read.py
  server/resources/db.py
  server/schemas/__init__.py
  server/schemas/user.py
Labels: backend, enhancement

#2 Frontend
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/Routing.js
  frontend/src/Styles/app.css
  frontend/src/index.js
Labels: enhancement, frontend

#4 Contact resource
  server/models/__init__.py
  server/models/contact.py
  server/models/user.py
  server/resources/api/user.py
  server/resources/crud/create.py
  server/resources/crud/read.py
  server/schemas/contact.py
  server/schemas/user.py
Labels: backend, enhancement

#5 Profile resource
  server/models/__init__.py
  server/models/enums.py
  server/models/profile.py
  server/models/types.py
  server/models/user.py
  server/resources/crud/create.py
  server/schemas/profile.py
  server/schemas/user.py
Labels: backend, enhancement

#7 Minor fixes
  server/models/contact.py
  server/models/profile.py
  server/models/user.py
  server/schemas/contact.py
  server/schemas/profile.py
  server/schemas/user.py
Labels: backend, enhancement

#9 Matching Algorithm
  server/models/__init__.py
  server/models/match.py
  server/models/user.py
  server/resources/api/__init__.py
  server/resources/api/match.py
  server/resources/crud/create.py
  server/resources/crud/custom.py
  server/schemas/contact.py
  server/schemas/match.py
  server/schemas/user.py
Labels: backend, enhancement

#11 Add more enums
  server/models/enums.py
  server/models/profile.py
  server/resources/crud/custom.py
  server/schemas/profile.py
Labels: backend, enhancement

#12 Backend
  server/.gitignore
  server/Dockerfile
  server/Pipfile
  server/Pipfile.lock
  server/README.md
  server/docker-compose.test.yml
  server/main.py
  server/models/__init__.py
  server/models/base.py
  server/models/contact.py
  server/models/enums.py
  server/models/match.py
  server/models/profile.py
  server/models/types.py
  server/models/user.py
  server/resources/__init__.py
  server/resources/api/__init__.py
  server/resources/api/match.py
  server/resources/api/user.py
  server/resources/crud/__init__.py
  server/resources/crud/create.py
  server/resources/crud/custom.py
  server/resources/crud/read.py
  server/resources/db.py
  server/schemas/__init__.py
  server/schemas/contact.py
  server/schemas/match.py
  server/schemas/profile.py
  server/schemas/user.py
Labels: backend, enhancement

#14 Match fixes
  server/models/match.py
  server/resources/api/match.py
  server/resources/crud/custom.py
  server/schemas/match.py
Labels: backend, enhancement

#16 Backend
  server/models/match.py
  server/resources/api/match.py
  server/resources/crud/custom.py
  server/schemas/match.py
Labels: backend, enhancement, frontend

#18 Add CORS permissions
  server/main.py
Labels: backend

#19 Backend
  server/main.py
Labels: backend

#20 Open CORS to all origins (so long security)
  server/main.py
Labels: backend

#21 Backend
  server/main.py
Labels: backend, enhancement

#22 Staging
  server/main.py
Labels: backend, enhancement

#23 Connect to DB URL in .env
  server/docker-compose.test.yml
  server/resources/db.py
Labels: backend, enhancement

#24 Backend
  server/docker-compose.test.yml
  server/resources/db.py
Labels: backend, enhancement
